{
  "hash": "fe743a875ad554d5b84810f59f00ded5",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n\n# Assignment  \n## Draw the DAG from the example in the previous chapter \n*  Imagine you are a business owner of four stores and you want to investigate if there is a benefit of having own parking spots in front of your store. And if there is a benefit, you would also like to know what size it has.\n*  At stores A and B, which are located in the city center, you don’t have any parking spots but at stores. C and D, located outside the city you do. Except for location and parking spots, the stores are very similar, i.e. they sell exactly the same goods, have the same size etc. \n\nVariables: \n\n*  L-> Location  \n*  P-> Parking Spots  \n*  A-> Store A\n*  B-> Store B\n*  C-> Store C\n*  D-> Store D\n*  S-> Sales\n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_f70459c9863b65fa9bc46afe6a605741'}\n\n```{.r .cell-code}\nlibrary(dagitty)\nlibrary(ggdag)\n\n# create DAG from dagitty\ndag_model <- 'dag {\nbb=\"0,0,1,1\"\nL [location,pos=\"0.9,0.6\"]\nP [exposure,pos=\"0.575,0.4\"]\nS [outcome,pos=\"0.9,0.4\"]\nD [pos=\"0.7,0.2\"]\nC [pos=\"0.7,0.3\"]\nB [pos=\"0.7,0.5\"]\nA [pos=\"0.7,0.6\"]\nL-> S\nP -> B\nP-> A\nP-> C\nP-> D\nA -> S\nB -> S\nC -> S\nD -> S\n}\n'\n# draw DAG\nggdag(dag_model) +\n  theme_dag()+\n  geom_dag_point(color = \"pink\") +\n  geom_dag_text(color = \"black\") +\n    geom_dag_edges(edge_color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## Perform the following steps:  \n*  A company sells a SaaS (Software as a service) to business clients that chose to subscribe to one of the three subscription levels, Starter, Premium or Elite, which provide different features at different price points (more storage and other capabilities). Starter has the least functionality, while Elite includes the most features.  \n*  Now imagine, you are working as an analyst for that company and are asked to examine the relationship between follow-up calls to the clients and their satisfaction with the product and service. Follow-up calls are voluntary and are just to help the client with possible problems and so on. Satisfaction is measured on a weekly basis by surveying the clients.\n\n### 1. Regress satisfaction on follow_ups  \n### 2. Regress satisfaction on follow_ups and account for subscription  \n\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_3859946ee03e552ba4245cec5982ada9'}\n\n```{.r .cell-code}\ndf <- data.frame(\n  follow_ups = c(8, 7, 8, 9, 10, 6, 7, 6, 8, 8, 0, 1, 2, 2, 3),\n  satisfaction = c(40, 45, 47, 44, 50, 55, 60, 62, 59, 65, 70, 74, 77, 74, 80),\n  subscription = c(\"Elite\", \"Elite\", \"Elite\", \"Elite\", \"Elite\", \"Premium+\", \"Premium+\", \"Premium+\", \"Premium+\", \"Premium+\", \"Premium\", \"Premium\", \"Premium\", \"Premium\", \"Premium\")\n)\n\n# Regress satisfaction on follow_ups\nmodel_follow_ups <- lm(satisfaction ~ follow_ups, data = df)\nsummary(model_follow_ups)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n\n```{.r .cell-code}\nsummary(model_follow_ups)$coefficients[\"follow_ups\", \"Pr(>|t|)\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.0002426524\n```\n:::\n\n```{.r .cell-code}\n# Regress satisfaction on follow_ups and account for subscription\nmodel_subscription <- lm(satisfaction ~ follow_ups + subscription, data = df)\nsummary(model_subscription)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n\n```{.r .cell-code}\nsummary(model_subscription)$coefficients[\"follow_ups\", \"Pr(>|t|)\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.0168153\n```\n:::\n:::\n\n## Compare the coefficients and find a possible explanation\n\n*  The coefficient for the satisfaction on follow ups is -3.3093\n*  The coefficient for the satisfaction on follow ups and account for subscription is 2.1944  \n*  When follow ups are being done, the level of satisfaction on those is low which is why the coefficient is negative. \n*  When you factor in the subscription the level of satisfaction increases which is why the coefficient is positive.\n*  Since the follow ups are to help the client with possible problems, when they are following up maybe the problems are not solved and the satisfaction of the call would be low. When people have subscriptions their problems might be easier to solve and therefore the overall satisfaction would increase.\n\n## Plot the data\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_aa6ccd7104fffd906c377fb0458326fa'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Scatter plot with regression line for satisfaction ~ follow_ups\nplot_follow_ups <- ggplot(df, aes(x = follow_ups, y = satisfaction)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"blue\") +\n  labs(title = \"Satisfaction vs. Follow-ups\",\n       x = \"Follow-ups\",\n       y = \"Satisfaction\")\n\n# Scatter plot with regression line for satisfaction ~ follow_ups + subscription\nplot_subscription <- ggplot(df, aes(x = follow_ups, y = satisfaction, color = subscription)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(title = \"Satisfaction vs. Follow-ups by Subscription\",\n       x = \"Follow-ups\",\n       y = \"Satisfaction\",\n       color = \"Subscription\")\n\n# Display the plots\nprint(plot_follow_ups)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(plot_subscription)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}