{
  "hash": "f3c759fac91c8c50abca484eb3837dd2",
  "result": {
    "markdown": "---\ntitle: \"Statistical Concepts\"\n---\n\n\n# Assignments  \n\n## Expected value, variance and standard deviation\n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-1_c6d30d797945f1970e26a31b805b53b9'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nrandom_vars <- readRDS(\"D:/GitHub/cdsba-pamoviedo/Causal_Data_Science_Data/random_vars.rds\")\n\n# Compute the expected value, variance and standard deviation for variable age\nmean_age <- mean(random_vars$age)\nmean_age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 33.471\n```\n:::\n\n```{.r .cell-code}\nvar_age <- var(random_vars$age)\nvar_age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 340.6078\n```\n:::\n\n```{.r .cell-code}\nsd_age <- sd(random_vars$age)\nsd_age\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 18.45556\n```\n:::\n\n```{.r .cell-code}\n#Compute the expected value, variance and standard deviation for variable income\nmean_income <- mean(random_vars$income)\nmean_income\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 3510.731\n```\n:::\n\n```{.r .cell-code}\nvar_income <- var(random_vars$income)\nvar_income\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 8625646\n```\n:::\n\n```{.r .cell-code}\nsd_income <- sd(random_vars$income)\nsd_income\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 2936.945\n```\n:::\n:::\n\n\n### Results \n*  Age expected value: 33.471  \n*  Age variance: 340.6078  \n*  Age standard deviation: 18.45556  \n\n*  Income expected value: 3510.731  \n*  Income variance: 8625646\n*  Income standard deviation: 2936.945\n\n## Does it make sense to compare standard deviations?  \n\n*  It doesn't make sense to compare them since they are individual data sets and the comparison would give us no insight.\n\n## Compute covariance and correlation \n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-2_e46b308d9a5e349a466b6bc96583e558'}\n\n```{.r .cell-code}\n#Compute the covariance and correlation between both variables\ncovariance <- cov(random_vars$age,random_vars$income)\ncovariance\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 29700.15\n```\n:::\n\n```{.r .cell-code}\ncorrelation <- cor(random_vars$age,random_vars$income)\ncorrelation\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.5479432\n```\n:::\n:::\n\n\n### Results\n*  Covariance: 29700.15  \n*  Correlation: 0.5479432\n\n## What measure is easier to interpret?  \n*  Covariance indicates the direction of the linear relationship between variables but it doesn't provide a standardized measure.  \n*  Correlation is a standardized measure that ranges between -1 and 1. With -1 indicating a perfect negative linear relationship, 0 indicating no linear relationship and 1 indicating a perfect positive linear relationship.  \n\n*  With the description above, it is easier to interpret the correlation since the values are fixed and we know that the 0.5479 represents a strong linear relation because it is closer to 1. The covariance value since it has no standardized measure, we are unable to know if it is representing a high or low value.  \n\n## Compute the conditional expected value for \n\n1.  $E[income|age<=18]$  \n2.  $E[income|age\\in[18,65)]$\n3.  $E[income|age>=65]$  \n\n\n::: {.cell hash='02_statistics_cache/html/unnamed-chunk-3_803a3286352e248b920b1e27d60a45ff'}\n\n```{.r .cell-code}\ncev1<- filter(random_vars,age<=18)\nmean_cev1 <- mean(cev1$income)\nmean_cev1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 389.6074\n```\n:::\n\n```{.r .cell-code}\ncev2<- filter(random_vars,age>=18&age<65)\nmean_cev2 <- mean(cev2$income)\nmean_cev2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 4685.734\n```\n:::\n\n```{.r .cell-code}\ncev3<- filter(random_vars,age>=65)\nmean_cev3<- mean(cev3$income)\nmean_cev3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1777.237\n```\n:::\n:::\n\n\n### Results \n\n1.  $E[income|age<=18]= 389.6074$  \n2.  $E[income|age\\in[18,65)]=4685.734$\n3.  $E[income|age>=65]=1777.237$  \n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}